apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-dev
  template:
    metadata:
      labels:
        app: user-service-dev
    spec:
      containers:
        - name: user-service
          image: user-service:dev
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-dev
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083